[package]
name = "reqwest-enum"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
